version: '2.1'
services:
  alerta:
    image: alerta
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=mongodb://root:123qewA@@127.0.1.1:27017/?connectTimeoutMS=300000
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io #default password: alerta
      - PLUGINS=reject,blackout
      - CUSTOMER_VIEWS=True
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qweA@
  db_dashboard:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123qweA@
  alertmanager:
    image: prom/alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - /etc/localtime:/etc/localtime
      - .alertmanager-conf:/etc/alertmanager 
      - .alertmanager-storage:/alertmanager    
